---
- name: Another network playbook example
  # The line below uses regex to parse the inventory file
  hosts: ~^arista
  # gather_facts ALWAYS runs setup.py (server module)
  gather_facts: no # v2.5=< no is default if network_cli is selected for connection
                   # if turned to yes you'll collect info about the local host :(

  tasks:
  # if we run this and have gather_facts set to no, then ansible_facts will be about our network devs
  - name: Harvest Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'

  - name: Push to the local system -- by special tag request only
    copy:
      # use the to_nice_json filter to display pretty json output
      content: "{{ ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
      # the inventory_hostname variable always resolves to the current host being iterated against
    tags:
            - never
            - grabfacts

    # dig into the data we want to reveal
  - name: Getting at network interfaces
    debug:
     var: ansible_facts.net_interfaces
