---
- name: Ansible Rest and Tags
  hosts: localhost
  gather_facts: false

  ## Lookup plugins can be used anywhere you can use templating in Ansible
  ## in a play, in variables files, or in Jinja2 templates for the template
  ## module
  vars:
          myrsakey: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"

  # Tags are easy! ansible-playbook example.yml --tags "keytime,astros" # would run everything
  # ansible-playbook example.yml --tags "astros" # would NOT run the task named 'Key prep'
  tasks:
          - name: Key Prep
            debug:
                msg: "Your RSA key is {{ myrsakey }}"
            tags:
                  - keytime
                  - vmprep
