---
- name: Playbook with the register keyword
  hosts: planet-express

  tasks:
          - name: "issue a trivial command"
            command: ls /lib/
            register: contentz_lib

          - name: "debug - display data returned"
            debug:
                    msg: "{{ contentz_lib }}"

          - name: "debug -standard error"
            debug:
                    msg: "{{ contentz_lib.stderr }}"

          - name: "debug - standard out"
            debug:
                    msg: "{{ contentz_lib.stdout }}"
